---

- hosts: all
  become: true
  tasks:
  - name: Update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "RedHat"
  - name: Install httpd package
    dnf:
      name: httpd
      state: latest 
    when: ansible_distribution == "RedHat"

  - name: Enable httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"

  - name: Add php support for apache
    dnf:
      name: php
      state: latest
    when: ansible_distribution == "RedHat"
