---

- hosts: all
  become: true
  tasks:

  - name: Install apache and php
    package:
      name:
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest 
      update_cache: yes

  - name: Enable httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"