---

- hosts: all
  become: true
  tasks:
  - name: Disable httpd
    service:
      name: httpd
      state: stopped
      enabled: no
  - name: Remove httpd and php package
    package:
      name: 
        - httpd
        - php
      state: absent 

