---

- hosts: all
  become: true
  pre_tasks:

  - name: Update repo cache (RedHat)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "RedHat"
  
  - name: Update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all 
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHMh3O3zRVYuMqAQkTG7Ky9pngc4FawR5eCxGLW5YKV+ ansible_key"

- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php on RedHat 
    tags: apache,apache2,ubuntu
    dnf:
      name:
        - httpd
        - php
      state: latest 
    when: ansible_distribution == "RedHat"
  
  - name: Install apache2 and php for Ubuntu servers
    tags: apache,redhat,httpd
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Enable httpd
    tags: redhat,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"
  
  - name: Change e-mail address for admin
    tags: apache,redhat,httpd
    lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: '^ServerAdmin'
      line: ServerAdmin somebody@somwhere.net
    when: ansible_distribution == "RedHat"
    register: httpd

  - name: restart httpd (RedHat)
    tags: apache,redhat,httpd
    service:
      name: httpd
      state: restarted
    when: httpd.changed

  - name: copy default html file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

    - name: Install MariaDB package (RedHat)
      tags: redhat,db,mariadb
      dnf:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Enable Mariadb on RedHat
      tags: redhat,db,mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"
    
    - name: install mariadb package (Ubuntu)
      tags: ubuntu,db,mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

- hosts: workstations
  become: true
  tasks:

    - name: Install unzip
      package:
        name: unzip

    - name: Install terraform
      unarchive: 
        src: https://releases.hashicorp.com/terraform/1.11.2/terraform_1.11.2_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
        mode: 0755
        owner: root
        group: root
