---

- hosts: all
  become: true
  pre_tasks:

  - name: Install updates (RedHat)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"
  
  - name: Install updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: web_servers
  become: true
  tasks:

  - name: Install apache and php on RedHat 
    tags: apache,apache2,ubuntu
    dnf:
      name:
        - httpd
        - php
      state: latest 
    when: ansible_distribution == "RedHat"
  
  - name: Install apache2 and php for Ubuntu servers
    tags: apache,redhat,httpd
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Enable httpd
    tags: redhat,httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "RedHat"

- hosts: db_servers
  become: true
  tasks:

    - name: Install MariaDB package (RedHat)
      tags: redhat,db,mariadb
      dnf:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "RedHat"

    - name: Enable Mariadb on RedHat
      tags: redhat,db,mariadb
      service:
        name: mariadb
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"
    
    - name: install mariadb package (Ubuntu)
      tags: ubuntu,db,mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest