- name: Install MariaDB package (RedHat)
  tags: redhat,db,mariadb
  dnf:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "RedHat"

- name: Enable Mariadb on RedHat
  tags: redhat,db,mariadb
  service:
    name: mariadb
    state: started
    enabled: yes
  when: ansible_distribution == "RedHat"
    
- name: install mariadb package (Ubuntu)
  tags: ubuntu,db,mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"